(()=>{
 const KEY='bumblebee-trials-v1';
 window.Trials={
  read:()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}},
  write:r=>localStorage.setItem(KEY,JSON.stringify(r)),
  start(mode,type){const run={id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(36),mode,type:type||'developer',startedAt:new Date().toISOString(),startMs:Date.now(),errors:0,status:'active'};sessionStorage.setItem('bb-run-'+mode,JSON.stringify(run));return run},
  current(mode){try{return JSON.parse(sessionStorage.getItem('bb-run-'+mode))}catch{return null}},
  error(mode){const r=this.current(mode);if(r){r.errors++;sessionStorage.setItem('bb-run-'+mode,JSON.stringify(r))}},
  finish(mode,status){const r=this.current(mode);if(!r)return null;r.elapsedSeconds=+((Date.now()-r.startMs)/1000).toFixed(1);r.status=status;r.endedAt=new Date().toISOString();delete r.startMs;const all=this.read();all.push(r);this.write(all);sessionStorage.removeItem('bb-run-'+mode);return r},
  reset(mode){sessionStorage.removeItem('bb-run-'+mode)}, clear(){localStorage.removeItem(KEY)},
  download(format){const rows=this.read();let body,type,name;if(format==='csv'){const h=['id','mode','type','startedAt','endedAt','elapsedSeconds','status','errors'];body=[h.join(','),...rows.map(r=>h.map(k=>JSON.stringify(r[k]??'')).join(','))].join('\n');type='text/csv';name='bumblebee-trials.csv'}else{body=JSON.stringify(rows,null,2);type='application/json';name='bumblebee-trials.json'}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
 };
 window.validateOrder=function(s){const d=BLOOM_DATA,c=d.constraints, errors=[];if(s.product!=='bumblebee')errors.push('Choose Bumblebee flowers.');if(+s.quantity!==c.quantity)errors.push('Quantity must be 12 bouquets.');if(s.wrap!==c.wrap)errors.push('The requested wrap is Ivory Garden Wrap (consult Grower Notes for its code).');const del=d.deliveries.find(x=>x.id===s.delivery);if(!del||del.name!==c.delivery)errors.push('Choose a delivery wholly within 09:00–11:00 and a total no more than $295.');if(s.date!==c.date)errors.push('Delivery date must be October 24, 2026.');if((s.recipient||'').trim()!==c.recipient)errors.push('Recipient must be Turnipseed Wedding.');if((s.venue||'').trim()!==c.venue)errors.push('Venue must be Meadow Hall.');if((s.email||'').trim().toLowerCase()!==c.email)errors.push('Contact email must be planner@example.com.');if((s.promo||'').trim()!==d.promo)errors.push('The promotion does not match the current Wedding Circular.');if(s.payment!=='invoice')errors.push('Choose Demo invoice.');return errors};
 window.totals=function(s){const qty=+s.quantity||0,sub=BLOOM_DATA.product.unitCents*qty,discount=(s.promo||'').trim()===BLOOM_DATA.promo?Math.floor(sub*10/100):0,del=BLOOM_DATA.deliveries.find(x=>x.id===s.delivery);return{sub,discount,delivery:del?del.cents:0,total:sub-discount+(del?del.cents:0)}};
 window.receiptHTML=function(s,mode){const t=totals(s), del=BLOOM_DATA.deliveries.find(x=>x.id===s.delivery),wrap=BLOOM_DATA.wraps.find(x=>x.code===s.wrap);return `<section class="receipt" data-total="${t.total}"><h2>Order confirmed</h2><p class="success">The order is complete.</p><dl><dt>Order ID</dt><dd>BB-${mode==='anti'?'A':'B'}-${String(Date.now()).slice(-6)}</dd><dt>Product</dt><dd>Bumblebee flowers</dd><dt>Quantity</dt><dd>${s.quantity} bouquets</dd><dt>Wrap</dt><dd>${wrap.name} (${wrap.code})</dd><dt>Delivery</dt><dd>October 24, 2026 · ${del.name} · ${del.window}</dd><dt>Recipient</dt><dd>${s.recipient}</dd><dt>Venue</dt><dd>${s.venue}</dd><dt>Email</dt><dd>${s.email}</dd><dt>Promotion</dt><dd>${BLOOM_DATA.promo} · 10% merchandise discount (${money(t.discount)})</dd><dt>Payment</dt><dd>Demo invoice — no financial information</dd><dt>Final total</dt><dd><strong>${money(t.total)}</strong></dd></dl></section>`}
})();
